services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: baches_rd_postgres
    restart: always
    environment:
      POSTGRES_DB: baches_rd_db
      POSTGRES_USER: baches_user
      POSTGRES_PASSWORD: baches_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U baches_user -d baches_rd_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: baches_rd_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bachesrd.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
