# DataSource Configuration (Dev - Local PostgreSQL Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/baches_rd_db
spring.datasource.username=baches_user
spring.datasource.password=baches_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.bachesrd.backend=DEBUG
